// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prwuivggifqmvonnnlzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByd3VpdmdnaWZxbXZvbm5ubHpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2Nzc3NjgsImV4cCI6MjA2MTI1Mzc2OH0.huBb3GPtDKPYxhC9Kpc15pNSq39MY92xWAiTWMYCJKA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);